### ISSUE TITLE
2342343b

### ISSUE THREAD

**Issue by danmoseley** [terrajobst/issue-form-test#3]
### Contact Details

asdfasdf

### What happened?

asdfasfdsadf A bug happened!

### Version

1.0.3 (Edge)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
dsafadsf
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by terrajobst** [comment]
![](https://media4.giphy.com/media/vPN3zK9dNL236/giphy.gif)
